name: Deploy Test Client Webb App code

on:
  workflow_dispatch:
    inputs:
      env_source:
        description: 'env name. accepted values [nonprod, qa]'     
        required: true
        default: 'qa'

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ github.event.inputs.env_source }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: change permissions for scripts
      run: |
        chmod +x ./script/set-variables.sh
    - name: execute script set-variables script
      run: |
        ./script/set-variables.sh ".github/workflows/environments/${{ github.event.inputs.env_source }}.json"
    - name: Setup DotNet ${{ env.dotnet_version }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet_version }}

    - name: 'Restore and Build'
      shell: bash
      run: |
        dotnet restore
        dotnet build --configuration Release --output ./output
        
    - name: 'Publish'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.function_name}}
        package: '${{ env.azure_web_app_package_path }}/output' 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
