name: Deploy Test Client Webb App code

on:
  workflow_dispatch:
    inputs:
      env_source:
        description: 'env name. accepted values [nonprod, qa]'     
        required: true
        default: 'qa'

env:
  AZURE_WEBAPP_NAME: ctc-nonprod-sfa-app  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ github.event.inputs.env_source }}
      
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main      
             
    - name: Setup DotNet 3.1.x Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Restore and Build'
      shell: bash
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
        
    - name: 'Publish'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
