name: Deploy Test Client Webb App code

on:
  workflow_dispatch:
    inputs:
      env_source:
        description: 'env name. accepted values [nonprod, qa]'     
        required: true
        default: 'qa'

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ github.event.inputs.env_source }}
      
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
          
    - name: Setup DotNet 3.1.x Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: 'Restore and Build'
      shell: bash
      run: |
        dotnet publish -c Release
        
    - name: 'Publish'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ctc-nonprod-sfa-app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
