name: .NET

on:
  workflow_dispatch:
    inputs:
      env_source:
        description: 'env name. accepted values [qa]'     
        required: true
        default: 'qa'
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.env_source }}

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: change permissions for scripts
      run: |
        chmod +x ./script/set-variables.sh
    - name: execute script set-variables script
      run: |
        ./script/set-variables.sh ".github/workflows/environments/${{ github.event.inputs.env_source }}.json"
    - name: Setup DotNet ${{ env.dotnet_version }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet_version }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: dotnet build --configuration Release --output ./output
