name: .NET

on:
  workflow_dispatch:
    inputs:
      env_source:
        description: 'env name. accepted values [nonprod, qa]'     
        required: true
        default: 'qa'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted]
    environment:
      name: ${{ github.event.inputs.env_source }}

    steps:
    - name: execute script set-variables script
      run: ./script/set-variables.sh ".github/workflows/environments/${{ github.event.inputs.env_source }}.json"
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Build
      run: dotnet build --configuration Release --output ./output
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
         app-name: '${{env.function_name}}'
         package: '${{ env.azure_web_app_package_path }}/output' 
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}       
